// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA2016:Forward the 'cancellationToken' parameter to the 'DeserializeAsync' method or pass in 'CancellationToken.None' explicitly to indicate intentionally not propagating the token", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.BotClient.RPCA``1(System.String,System.IO.Stream,System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.BotClient.RPCA``1(System.String,System.IO.Stream,System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.BotClient.RPCA``1(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: SuppressMessage("Build", "CA2016:Forward the 'cancellationToken' parameter to the 'DeserializeAsync' method or pass in 'CancellationToken.None' explicitly to indicate intentionally not propagating the token", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.BotClient.RPCA``1(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.BotClient.RPCAF``1(System.String,System.Object,System.Text.Json.JsonSerializerOptions,System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: SuppressMessage("Build", "CA2016:Forward the 'cancellationToken' parameter to the 'DeserializeAsync' method or pass in 'CancellationToken.None' explicitly to indicate intentionally not propagating the token", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.BotClient.RPCAF``1(System.String,System.Object,System.Text.Json.JsonSerializerOptions,System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: SuppressMessage("Build", "CA1031:Modify 'OnUpdate' to catch a more specific allowed exception type, or rethrow the exception", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.BotTemplate.OnUpdate(Telegram.BotAPI.Getting_updates.Update,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Build", "CA2016:Forward the 'cancellationToken' parameter to the 'SerializeAsync' method or pass in 'CancellationToken.None' explicitly to indicate intentionally not propagating the token", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.Inline_mode.Inlinemode.AnswerInlineQueryAsync(Telegram.BotAPI.BotClient,Telegram.BotAPI.Inline_mode.AnswerInlineQueryArgs,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Build", "CA2016:Forward the 'cancellationToken' parameter to the 'SerializeAsync' method or pass in 'CancellationToken.None' explicitly to indicate intentionally not propagating the token", Justification = "<Pending>", Scope = "member", Target = "~M:Telegram.BotAPI.Telegram_Passport.TelegramPassport.SetPassportDataErrorsAsync(Telegram.BotAPI.BotClient,System.Int32,Telegram.BotAPI.Telegram_Passport.PassportElementError[],System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Build", "CA1032:Add the following constructor to BotRequestException: public BotRequestException(string message)", Justification = "<Pending>", Scope = "type", Target = "~T:Telegram.BotAPI.BotRequestException")]
